name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Run static analysis
      run: |
        dotnet nuget install Microsoft.Net.Compilers   # Install C# and VB compilers
        dotnet nuget install Microsoft.CodeAnalysis    # Install Language APIs and Services
        dotnet nuget install Microsoft.CodeAnalysis.FxCopAnalyzers
        dotnet msbuild 'Developers/Unity Project/Spooksville/Assembly-CSharp.csproj' /p:RunCodeAnalysis=true

